language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit
  - vendor/bin/php-cs-fixer --diff --dry-run -vv fix

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
